function f = robot_f_generated(q1,q2,q3)
%ROBOT_F_GENERATED
%    F = ROBOT_F_GENERATED(Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    23-Apr-2026 14:15:59

t2 = q1+q2;
t4 = -q1;
t5 = -q2;
t3 = q3+t2;
t6 = q1+t5;
t7 = q2+q3+t4;
et1 = cos(t2).*6.25e-2+cos(t3).*4.3e-2;
et2 = cos(t6).*6.25e-2+cos(t7).*4.3e-2;
et3 = sin(t2).*6.25e-2+sin(t3).*4.3e-2;
et4 = sin(t6).*6.25e-2-sin(t7).*4.3e-2;
f = [et1+et2;et3+et4;sin(q2+q3).*(4.3e+1./5.0e+2)+sin(q2)./8.0+1.3e+1./2.0e+2];
end
