function out1 = robot_G_generated(in1)
%robot_G_generated
%    OUT1 = robot_G_generated(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    23-Apr-2026 14:15:59

q2 = in1(2,:);
q3 = in1(3,:);
t2 = q2+q3;
t3 = cos(t2);
t4 = t3.*1.2781449e-1;
out1 = [0.0;t4+cos(q2).*2.43410625e-1;t4];
end
