function out1 = robot_M_generated(in1)
%robot_M_generated
%    OUT1 = robot_M_generated(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    23-Apr-2026 14:15:59

q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q3);
t3 = q2.*2.0;
t4 = q3.*2.0;
t5 = cos(t3);
t6 = q3+t3;
t8 = t3+t4;
t10 = t2.*9.972451966306791e-20;
t11 = t2.*1.994490393261358e-19;
t14 = t2.*1.628625e-3;
t7 = cos(t6);
t9 = cos(t8);
et1 = t10;
et2 = 1.067273970438522e-19;
t15 = et1+et2;
et3 = t11;
et4 = 3.484675725005433e-19;
t16 = et3+et4;
t12 = t7.*3.053182845047085e-36;
t13 = t9.*3.150884696088592e-36;
et5 = t12+t13+t14;
et6 = 1.742990666666667e-3;
t17 = et5+et6;
et7 = t2.*1.628625e-3;
et8 = t5.*1.973958333333333e-3;
et9 = t7.*1.628625e-3;
et10 = t9.*8.714953333333333e-4;
et11 = 2.887351583333333e-3;
et12 = t2.*3.25725e-3;
et13 = t5.*7.242492309827037e-36;
et14 = t7.*6.10636569009417e-36+t13;
et15 = 5.690907333333333e-3;
et16 = t13;
et17 = 1.742990666666667e-3;
out1 = reshape([et7+et8+et9+et10+et11,t16,t15,t16,et12+et13+et14+et15,t17,t15,t17,et16+et17],[3,3]);
end
